from typing import Optional, Dict, Any, Literal, List
from pydantic import BaseModel, Field
from datetime import datetime


class MonitoringDecision(BaseModel):
    """Structured supervisor decision output from Monitor Agent."""
    system_status: Literal["HEALTHY", "DEGRADED", "CRITICAL_ANOMALY"] = Field(
        default="HEALTHY",
        description="Overall health status assessment"
    )
    anomaly_detected: bool = Field(
        default=False,
        description="Whether an operational anomaly or failure is detected"
    )
    anomaly_type: Optional[str] = Field(
        default=None,
        description="Type of anomaly (e.g. RETRY_LOOP, LATENCY_SPIKE, RECONCILIATION_DESYNC, UNEXPECTED_STATE)"
    )
    severity: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"] = Field(
        default="LOW",
        description="Severity level of the incident"
    )
    root_cause: str = Field(
        default="System nominal.",
        description="LLM diagnosis of the root cause based on telemetry, logs, and events"
    )
    evidence: Dict[str, Any] = Field(
        default_factory=dict,
        description="Specific events, metrics, or logs supporting the diagnosis"
    )
    recommended_recovery: str = Field(
        default="Standby.",
        description="LLM recommendation for mitigation or recovery"
    )
    confidence: float = Field(
        default=0.9,
        ge=0.0,
        le=1.0,
        description="Confidence in diagnosis"
    )
    human_intervention_required: bool = Field(
        default=False,
        description="Whether immediate human operator intervention is deemed necessary"
    )


class RecoveryPlan(BaseModel):
    """Structured recovery strategy generated by Recovery Agent."""
    action: Literal[
        "pause_agent",
        "switch_to_fallback",
        "retry_operation",
        "create_incident",
        "request_human_approval",
        "notify_operator",
        "rollback_safe_operation",
        "no_action"
    ] = Field(
        default="no_action",
        description="Selected recovery strategy"
    )
    reason: str = Field(
        default="No recovery action required.",
        description="Detailed rationale for choosing this recovery action"
    )
    expected_effect: str = Field(
        default="Restores normal operations.",
        description="Anticipated outcome after executing the action"
    )
    risk: Literal["LOW", "MEDIUM", "HIGH"] = Field(
        default="LOW",
        description="Risk level of executing this recovery action"
    )
    requires_human_approval: bool = Field(
        default=False,
        description="Whether human-in-the-loop signoff is required before execution"
    )
    verification_plan: str = Field(
        default="Verify subsystem telemetry.",
        description="How the system will verify whether recovery succeeded"
    )
    action_parameters: Dict[str, Any] = Field(
        default_factory=dict,
        description="Parameters required to execute the action"
    )


class IncidentResponse(BaseModel):
    incident_id: str
    title: str
    severity: str
    status: str
    detected_by: str
    root_cause: Optional[str] = None
    evidence: Dict[str, Any] = Field(default_factory=dict)
    recovery_plan: Dict[str, Any] = Field(default_factory=dict)
    recovery_result: Dict[str, Any] = Field(default_factory=dict)
    human_review_required: bool
    created_at: datetime
    resolved_at: Optional[datetime] = None


class IncidentApprovalRequest(BaseModel):
    operator_name: str = Field(..., json_schema_extra={"example": "operator:alex"})
    reason: Optional[str] = Field(default="Approved after operator inspection", json_schema_extra={"example": "Reviewed and safe to proceed"})


class IncidentRejectRequest(BaseModel):
    operator_name: str = Field(..., json_schema_extra={"example": "operator:alex"})
    reason: str = Field(..., json_schema_extra={"example": "Unsafe to retry; escalating to level 3 support"})
